title: Rangsiman Ketkaew
subtitle: Ph.D. Student in Theoretical Chemistry at UZH
description: >- # this means to ignore newlines until "baseurl:"
  Rangsiman Ketkaew's website: Ph.D. Student in Theoretical Chemistry at University of Zurich
baseurl: "" # the subpath of site, e.g. /blog
url: "https://rangsimanketkaew.github.io" # the base hostname & protocol for site, e.g. http://example.com

author_logo: /assets/img/profile.png
author: Rangsiman Ketkaew
author_email: "rangsiman1993@gmail.com"
author_location: Zurich, Switzerland
author_website_url: "https://rangsimanketkaew.github.io"

# Disqus for commenting under the post
disqus_shortname: rangsiman-ketkaew

# social links
twitter_username: rangsiman1993
github_username: rangsimanketkaew
facebook_username: rangsiman1993
linkedin_username: rangsiman1993

# Google Analytics
google_analytics: UA-55803297-6

# Additional plugins
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

# Build setting
permalink: pretty # remove *.html extension from generated link
markdown: kramdown

highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  syntax_highlighter_opts: {span: {disable: true}}
  math_engine: mathjax

